export const GET_ACTIVATES = "GET_ACTIVATE";
export const GET_ACTIVATES_SUCCESS = "GET_ACTIVATE_SUCCESS";
export const GET_ACTIVATES_FAILED = "GET_ACTIVATE_FAILED";


export const GET_STATIONS = "GET_STATIONS";
export const GET_STATIONS_SUCCESS = "GET_STATIONS_SUCCESS";
export const GET_STATIONS_FAILED = "GET_STATIONS_FAILED";


export const ADD_ACTIVATE = "ADD_ACTIVATE";
export const ADD_ACTIVATE_SUCCESS = "ADD_ACTIVATE_SUCCESS";
export const ADD_ACTIVATE_FAILED = "ADD_ACTIVATE_FAILED";


export const DELETE_ACTIVATE = "DELETE_ACTIVATE";
export const DELETE_ACTIVATE_SUCCESS = "DELETE_ACTIVATE_SUCCESS";
export const DELETE_ACTIVATE_FAILED = "DELETE_ACTIVATE_FAILED";

