export const GET_NOTIFICATION_LIST = 'GET_NOTIFICATION_LIST';
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS';
export const GET_NOTIFICATION_LIST_FAILED = 'GET_NOTIFICATION_LIST_FAILED';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILED = 'DELETE_NOTIFICATION_FAILED';

export const DELETE_ALL_NOTIFICATION = 'DELETE_ALL_NOTIFICATION';
export const DELETE_ALL_NOTIFICATION_SUCCESS = 'DELETE_ALL_NOTIFICATION_SUCCESS';
export const DELETE_ALL_NOTIFICATION_FAILED = 'DELETE_ALL_NOTIFICATION_FAILED';

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";