export const GET_ROOM_LIST = "GET_ROOM_LIST";
export const GET_ROOM_LIST_SUCCESS = "GET_ROOM_LIST_SUCCESS";
export const GET_ROOM_LIST_FAILED = "GET_ROOM_LIST_FAILED";

export const GET_CURR_ROOM_INFO = "GET_ROOM_INFO";
export const GET_CURR_ROOM_INFO_SUCCESS = "GET_ROOM_INFO_SUCCESS";
export const GET_CURR_ROOM_INFO_FAILED = "GET_ROOM_INFO_FAILED";

export const SET_CURR_ROOM = "SET_CURR_ROOM";

export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";

export const UPDATE_ROOM = "UPDATE_ROOM";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILED = "UPDATE_ROOM_FAILED";

export const DELETE_ROOM = "DELETE_ROOM";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED";

