export const GET_CURR_ROOM_SENSOR_MAP = "GET_CURR_ROOM_SENSOR_MAP";
export const GET_CURR_ROOM_SENSOR_MAP_SUCCESS = "GET_CURR_ROOM_SENSOR_MAP_SUCCESS";
export const GET_CURR_ROOM_SENSOR_MAP_FAILED = "GET_CURR_ROOM_SENSOR_MAP_FAILED";

export const ADD_SENSOR = "ADD_SENSOR";
export const ADD_SENSOR_SUCCESS = "ADD_SENSOR_SUCCESS";
export const ADD_SENSOR_FAILED = "ADD_SENSOR_FAILED";

export const UPDATE_SENSOR = "UPDATE_SENSOR";
export const UPDATE_SENSOR_SUCCESS = "UPDATE_SENSOR_SUCCESS";
export const UPDATE_SENSOR_FAILED = "UPDATE_SENSOR_FAILED";

export const DELETE_SENSOR = "DELETE_SENSOR";
export const DELETE_SENSOR_SUCCESS = "DELETE_SENSOR_SUCCESS";
export const DELETE_SENSOR_FAILED = "DELETE_SENSOR_FAILED";