export const GET_USER_ACCESS = "GET_USER_ACCESS";
export const GET_USER_ACCESS_SUCCESS = "GET_USER_ACCESS_SUCCESS";
export const GET_USER_ACCESS_FAILED = "GET_USER_ACCESS_FAILED";

export const GET_ACCESS = "ADD_ACCESS";
export const GET_ACCESS_SUCCESS = "ADD_ACCESS_SUCCESS";
export const GET_ACCESS_FAILED = "ADD_ACCESS_FAILED";

export const ADD_ACCESS = "ADD_ACCESS";
export const ADD_ACCESS_SUCCESS = "ADD_ACCESS_SUCCESS";
export const ADD_ACCESS_FAILED = "ADD_ACCESS_FAILED";

export const UPDATE_ACCESS = "UPDATE_ACCESS";
export const UPDATE_ACCESS_SUCCESS = "UPDATE_ACCESS_SUCCESS";
export const UPDATE_ACCESS_FAILED = "UPDATE_ACCESS_FAILED";

export const REPLY_ACCESS = "REPLY_ACCESS";
export const REPLY_ACCESS_SUCCESS = "REPLY_ACCESS_SUCCESS";
export const REPLY_ACCESS_FAILED = "REPLY_ACCESS_FAILED";

export const DELETE_ACCESS = "DELETE_ACCESS";
export const DELETE_ACCESS_SUCCESS = "DELETE_ACCESS_SUCCESS";
export const DELETE_ACCESS_FAILED = "DELETE_ACCESS_FAILED";
