export const GET_AREA_DATA = "GET_AREA_DATA";
export const GET_AREA_DATA_SUCCESS = "GET_AREA_DATA_SUCCESS";
export const GET_AREA_DATA_FAILED = "GET_AREA_DATA_FAILED";

export const GET_CURRENT_DATA = "GET_CURRENT_DATA";
export const GET_CURRENT_DATA_SUCCESS = "GET_CURRENT_DATA_SUCCESS";
export const GET_CURRENT_DATA_FAILED = "GET_CURRENT_DATA_FAILED";

export const GET_SENSOR_DATA = "GET_SENSOR_DATA";
export const GET_SENSOR_DATA_SUCCESS = "GET_SENSOR_DATA_SUCCESS";
export const GET_SENSOR_DATA_FAILED = "GET_SENSOR_DATA_FAILED";

export const GET_CUBE_DATA = "GET_CUBE_DATA";
export const GET_CUBE_DATA_SUCCESS = "GET_CUBE_DATA_SUCCESS";
export const GET_CUBE_DATA_FAILED = "GET_CUBE_DATA_FAILED";