export const GET_AREAS = "GET_AREAS";
export const GET_AREAS_SUCCESS = "GET_AREAS_SUCCESS";
export const GET_AREAS_FAILED = "GET_AREAS_FAILED";

export const GET_AREA_INFO = "GET_AREA_INFO";
export const GET_AREA_INFO_SUCCESS = "GET_AREA_INFO_SUCCESS";
export const GET_AREA_INFO_FAILED = "GET_AREA_INFO_FAILED";

export const ADD_AREA = "ADD_AREA";
export const ADD_AREA_SUCCESS = "ADD_AREA_SUCCESS";
export const ADD_AREA_FAILED = "ADD_AREA_FAILED";

export const ADD_MONITOR = "ADD_MONITOR";
export const ADD_MONITOR_SUCCESS = "ADD_MONITOR_SUCCESS";
export const ADD_MONITOR_FAILED = "ADD_MONITOR_FAILED";

export const UPDATE_AREA = "UPDATE_AREA";
export const UPDATE_AREA_SUCCESS = "UPDATE_AREA_SUCCESS";
export const UPDATE_AREA_FAILED = "UPDATE_AREA_FAILED";

export const UPDATE_MONITOR = "UPDATE_MONITOR";
export const UPDATE_MONITOR_SUCCESS = "UPDATE_MONITOR_SUCCESS";
export const UPDATE_MONITOR_FAILED = "UPDATE_MONITOR_FAILED";

export const DELETE_AREA = "DELETE_AREA";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCESS";
export const DELETE_AREA_FAILED = "DELETE_AREA_FAILED";

export const DELETE_MONITOR = "DELETE_MONITOR";
export const DELETE_MONITOR_SUCCESS = "DELETE_MONITOR_SUCCESS";
export const DELETE_MONITOR_FAILED = "DELETE_MONITOR_FAILED";
