export const GET_SENSORS = "GET_SENSORS";
export const GET_SENSORS_SUCCESS = "GET_SENSORS_SUCCESS";
export const GET_SENSORS_FAILED = "GET_SENSORS_FAILED";

export const GET_SENSORS_NOT_USED = "GET_SENSORS_NOT_USED";
export const GET_SENSORS_NOT_USED_SUCCESS = "GET_SENSORS_NOT_USED_SUCCESS";
export const GET_SENSORS_NOT_USED_FAILED = "GET_SENSORS_NOT_USED_FAILED";